
[terminal.shell]
program = "/bin/fish"

[window]
padding = { x = 4, y = 4 }
dynamic_padding = true

[font.normal]
family = "FiraCode Nerd Font Mono"

[font]
size = 12

[general]
import = [
	"~/.config/alacritty/themes/kanagawa_wave.toml"
]

[terminal]

# line spacing:
# [font]
# offset.x = 0
# offset.y = 2
# glyph_offset.y = 1
