import = [
	"~/.config/alacritty/themes/kanagawa_wave.toml"
]

[shell]
program = "/bin/fish"

[window]
padding = { x = 4, y = 4 }
dynamic_padding = true

[font.normal]
family = "FiraCode Nerd Font"

# [font]
# offset.x = 0
# offset.y = 2
# glyph_offset.y = 1
